# Gradle Properties
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Gradle Plugins
loom_version = 1.10-SNAPSHOT
moddev_version = 2.0.33-beta
versioning_version = 1.0.0
kpublish_version = 1.0.0
submodule_version = 0.8.0
remapcheck_version = 0.4.0

# Fabric Properties
# check these on https://fabricmc.net/develop
java_version=21
minecraft_version = 1.21.5
parchment_mc_version = 1.21.4
parchment_version = 2025.03.23
fabric_loader_version = 0.16.10
neoforge_version = 21.5.24-beta

# Mod Properties
project_version = 0.2.99+1.21.4.local
maven_group = com.kneelawk.kregistry
archives_base_name = kregistry
javadoc_package_name = com/kneelawk/kregistry

# Dependencies
fapi_version = 0.119.6+1.21.5
common_events_version = 1.3.0+1.21.4

# Runtime Only Dependencies
mod_menu_version = 13.0.0-beta.1

# Javadoc Dependencies
jetbrains_annotations_version = 24.0.0
