modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "KRegistry Lite"
authors = "Kneelawk"
description = "Lightweight Registry alternatives."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"
